### ISSUE TITLE
Process detection error

### ISSUE THREAD

**Issue by kyrox02** [CXWorld/CapFrameX#129] opened 2020-07-18 19:30 UTC
not showing fps + scanning for process

![ewv](https://user-images.githubusercontent.com/27238585/87860461-50e06b80-c946-11ea-9e41-b58995d23bb0.png)

**Comment by Taxxor90** [comment] 2020-07-18 23:13
"Scanning for process..." means PresentMon didn't find the process, either because it's on the ignore list or it failed to recognize it.

I assume there is also nothing showing up in your "Running processes" list?
The FPS value is bound to the process, so it's 0 if your list is empty.

We've optimized the process of PresentMon getting the current processes throughout this beta phase so if you downloaded it before the 16.7. you could try again with the current version, which is now up to date.

**Comment by kyrox02** [comment] 2020-07-20 15:41
can u share complete binary i dont have visual studio installed in my pc

**Comment by Taxxor90** [comment] 2020-07-20 15:42
Just download the beta again it's already updated

**Comment by kyrox02** [comment] 2020-07-20 15:59
yes i had spyshelter i remove it but still same issue but when i try record without capframex its work

![download](https://user-images.githubusercontent.com/27238585/87959191-2a900c80-cabb-11ea-9e80-9ba7ab7a51fd.png)

**Comment by kyrox02** [comment] 2020-07-20 16:54
seems capframex not working only presetmon64 the only way to capture games 

![download](https://user-images.githubusercontent.com/27238585/87964391-d38e3580-cac2-11ea-9318-dc4dce0219c7.png)

**Comment by DevTechProfile** [comment] 2020-07-20 18:13
Did you really install the latest beta? If still have the same issue please upload the latest logs under Documents/CapFrameX/Logs.

**Comment by kyrox02** [comment] 2020-07-20 18:29
[CapFrameX_002.log](https://github.com/CXWorld/CapFrameX/files/4949430/CapFrameX_002.log)
[CapFrameX_003.log](https://github.com/CXWorld/CapFrameX/files/4949431/CapFrameX_003.log)

there we go  yes i install the latest beta

**Comment by DevTechProfile** [comment] 2020-07-20 20:33
Open a game and make a screenshot of PresentMon please. Just open it and do not prompt any capture commands.

**Comment by kyrox02** [comment] 2020-07-20 20:41
![download](https://user-images.githubusercontent.com/27238585/87984334-815d0c80-cae2-11ea-9e37-80cd04dbd48e.png)

**Comment by DevTechProfile** [comment] 2020-07-21 08:20
I've integrated further logging to check the data stream from PresentMom. This is not a bugfix it just give us more information: https://nexus.cluster.the.mind-blowing.dev/service/rest/repository/browse/CapFrameX/release__1.5.3/21.07.2020/

Thanks for your support!

**Comment by kyrox02** [comment] 2020-07-21 09:28
{"@t":"2020-07-21T09:24:35.8280896Z","@mt":"CapFrameX {version} started","version":"1.5.3.7","SourceContext":"Microsoft.Extensions.Logging.ILogger"}
{"@t":"2020-07-21T09:24:36.2235895Z","@mt":"{componentName} Ready","@l":"Debug","componentName":"SensorService","SourceContext":"CapFrameX.Sensor.SensorService"}
{"@t":"2020-07-21T09:24:37.1825892Z","@mt":"Now observing directory: {path}","path":"C:\\Users\\User\\Documents\\CapFrameX\\Captures","SourceContext":"CapFrameX.Data.RecordDirectoryObserver"}
{"@t":"2020-07-21T09:24:37.5350891Z","@mt":"{componentName} Ready","@l":"Debug","componentName":"OverlayService","SourceContext":"CapFrameX.Overlay.OverlayService"}
{"@t":"2020-07-21T09:24:37.5520893Z","@mt":"{viewName} Ready","@l":"Debug","viewName":"CaptureViewModel","SourceContext":"CapFrameX.ViewModel.CaptureViewModel"}
{"@t":"2020-07-21T09:24:37.6440891Z","@mt":"PresentMon sucessfully started","SourceContext":"CapFrameX.PresentMonInterface.PresentMonCaptureService"}
{"@t":"2020-07-21T09:26:14.7235517Z","@mt":"Changing observed directory","@l":"Debug","SourceContext":"CapFrameX.Data.RecordDirectoryObserver"}
{"@t":"2020-07-21T09:26:14.7380520Z","@mt":"Now observing directory: {path}","path":"C:\\CAPFRAME","SourceContext":"CapFrameX.Data.RecordDirectoryObserver"}
{"@t":"2020-07-21T09:26:14.9535572Z","@mt":"Error Creating FileRecordInfo of {path}","@l":"Error","@x":"System.InvalidOperationException: Sequence contains no elements\r\n   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)\r\n   at CapFrameX.Data.RecordManager.LoadSessionFromCSV(FileInfo csvFile)\r\n   at CapFrameX.Data.RecordManager.<>c__DisplayClass20_0.<GetFileRecordInfo>b__0(Int64 _)\r\n   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnNext(TSource value) in d:\\a\\1\\s\\Rx.NET\\Source\\src\\System.Reactive\\Linq\\Observable\\SelectMany.cs:line 865","path":"C:\\CAPFRAME\\PresentMon-2020-07-20-20-24.csv","SourceContext":"CapFrameX.Data.RecordManager"}
{"@t":"2020-07-21T09:26:14.9535572Z","@mt":"Error Creating FileRecordInfo of {path}","@l":"Error","@x":"System.InvalidOperationException: Sequence contains no elements\r\n   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)\r\n   at CapFrameX.Data.RecordManager.LoadSessionFromCSV(FileInfo csvFile)\r\n   at CapFrameX.Data.RecordManager.<>c__DisplayClass20_0.<GetFileRecordInfo>b__0(Int64 _)\r\n   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnNext(TSource value) in d:\\a\\1\\s\\Rx.NET\\Source\\src\\System.Reactive\\Linq\\Observable\\SelectMany.cs:line 865","path":"C:\\CAPFRAME\\PresentMon-2020-07-21-02-09.csv","SourceContext":"CapFrameX.Data.RecordManager"}
{"@t":"2020-07-21T09:26:15.0195518Z","@mt":"Getting Systeminfos","SourceContext":"CapFrameX.Data.RecordManager"}
{"@t":"2020-07-21T09:26:15.0190495Z","@mt":"Getting Systeminfos","SourceContext":"CapFrameX.Data.RecordManager"}
{"@t":"2020-07-21T09:26:15.3380517Z","@mt":"Getting Systeminfos","SourceContext":"CapFrameX.Data.RecordManager"}
{"@t":"2020-07-21T09:26:51.5120378Z","@mt":"PresentMon sucessfully started","SourceContext":"CapFrameX.PresentMonInterface.PresentMonCaptureService"}


error: failed to enable DWM provider (error=4201).

**Comment by DevTechProfile** [comment] 2020-07-21 09:41
Please use the default directory and leave it empty. I would like to check the process detection first. Just start CX and a game. Is there now an entry in the process list on the capture page?

**Comment by kyrox02** [comment] 2020-07-21 09:45
> Please use the default directory and leave it empty. I would like to check the process detection first. Just start CX and a game. Is there now an entry in the process list on the capture page?

yes

![download](https://user-images.githubusercontent.com/27238585/88039230-f581c980-cb4f-11ea-9a98-b61f2aa90405.png)

the only way to capture the game is using presetmon build 105 without capframex

**Comment by DevTechProfile** [comment] 2020-07-21 09:46
And now share the log please.

**Comment by kyrox02** [comment] 2020-07-21 09:48
[CapFrameX.log](https://github.com/CXWorld/CapFrameX/files/4952634/CapFrameX.log)
[CapFrameX_001.log](https://github.com/CXWorld/CapFrameX/files/4952635/CapFrameX_001.log)

**Comment by DevTechProfile** [comment] 2020-07-21 09:51
And Valorant is running too?

**Comment by kyrox02** [comment] 2020-07-21 09:51
> And Valorant is running too?

yes

**Comment by DevTechProfile** [comment] 2020-07-21 09:56
One little test at least. Close game and CX. Go to C:\Users\%profilename%\AppData\Local\CapFrameX and delete all "CapFrameX.exe_Url" directories. Restart game and CX. Is the process list still empty?

**Comment by kyrox02** [comment] 2020-07-21 10:00
![download](https://user-images.githubusercontent.com/27238585/88040784-13e8c480-cb52-11ea-87a3-492ff1401c30.png)


Yes

**Comment by DevTechProfile** [comment] 2020-07-22 06:42
If you delete the configs, Capture Hotkey is F11 and Capture time is 0. Did you really delete the configs?

**Comment by kyrox02** [comment] 2020-07-22 14:44
yes its restore to F11 and 0 i just set it to F12 and 10 sec

i didnt change any global character format/encoding settings

**Comment by Taxxor90** [comment] 2020-07-22 14:54
Well with this version, once you start a game, there should be a log entry when the first dataline was recieved from PresentMon.

That entry is not present in yur latest log files, meaning PresentMon doesn't seem to be pushing anything to CX so I'm afraid there's nothing we could do from our end since we don't have control over PresentMon other than starting and closing it.

**Comment by kyrox02** [comment] 2020-07-22 15:30
> Well with this version, once you start a game, there should be a log entry when the first dataline was recieved from PresentMon.
> 
> That entry is not present in yur latest log files, meaning PresentMon doesn't seem to be pushing anything to CX so I'm afraid there's nothing we could do from our end since we don't have control over PresentMon other than starting and closing it.

its okay i can record with presentmon without capframex works great

**Comment by Taxxor90** [comment] 2020-07-22 16:41
If you don't mind, could you try a record with OCAT? 

They're using PresentMon too and it would be interesting to know if that works for you.

**Comment by kyrox02** [comment] 2020-07-22 17:01
OCAT using globalhooks injection which cause the game to stop work like valorant  the anticheat dont like it  but every game i try work great with ocat to thanks for let me know

**Comment by kyrox02** [comment] 2020-07-22 17:17
![download](https://user-images.githubusercontent.com/27238585/88207386-657b7700-cc58-11ea-8767-5f6b9dcdacc5.png)

**Comment by kyrox02** [comment] 2020-07-22 17:39
> If you don't mind, could you try a record with OCAT?
> 
> They're using PresentMon too and it would be interesting to know if that works for you. If yes, CX also can handle the OCAT files ^^

thank u so muchhhh OCAT workkk with capframex im closing the topic thankss

**Closed** 2020-07-22 17:39 UTC
